import { NextResponse } from 'next/server';
import { createHmac } from 'crypto';
import { prisma } from '@/lib/prisma';
import { fetchPullRequestDiff, postPRReviewComment } from '@/lib/github';
import { reviewDiff, ReviewResult } from '@/lib/ai';

function verifySignature(payload: string, signature: string | null, secret: string): boolean {
  if (!signature) return false;
  const algo = signature.startsWith('sha256=') ? 'sha256' : 'sha1';
  const expected = algo === 'sha256' ? 'sha256=' : 'sha1=';
  const hmac = createHmac(algo, secret).update(payload).digest('hex');
  return signature === expected + hmac;
}

function logger(message: string, data?: unknown) {
  if (process.env.NODE_ENV !== 'production') {
    const ts = new Date().toISOString();
    if (data) {
      console.log(`[webhook] ${ts} ${message}`, data);
    } else {
      console.log(`[webhook] ${ts} ${message}`);
    }
  }
}

/**
 * Format AI review result into a GitHub-friendly Markdown comment.
 */
function formatReviewComment(result: ReviewResult, prTitle: string): string {
  const { qualityScore, summary, findings } = result;

  let body = `## 🤖 PRwise AI Review\n\n`;
  body += `**PR**: ${prTitle}\n\n`;
  body += `**Quality Score**: ${qualityScore}/100\n\n`;
  body += `> ${summary}\n\n`;

  if (findings.length > 0) {
    body += `### 📝 Findings (${findings.length})\n\n`;

    findings.forEach((f) => {
      const icon = f.severity === 'ERROR' ? '🔴' : f.severity === 'WARNING' ? '🟡' : '🔵';
      body += `${icon} **${f.title}**\n`;
      if (f.filePath) {
        body += `- 📁 File: \`${f.filePath}\``;
        if (f.lineStart) body += ` (line ${f.lineStart})`;
        body += '\n';
      }
      body += `- ${f.description}\n`;
      if (f.suggestion) {
        body += `- 💡 Suggestion: ${f.suggestion}\n`;
      }
      body += '\n';
    });
  } else {
    body += '✅ No issues found. Code looks great!\n';
  }

  body += '---\n*Generated by PRwise AI*';
  return body;
}

export async function POST(request: Request) {
  const text = await request.text();
  const signature = request.headers.get('x-hub-signature-256');
  const event = request.headers.get('x-github-event');
  const webhookSecret = process.env.GITHUB_WEBHOOK_SECRET;

  if (webhookSecret && !verifySignature(text, signature, webhookSecret)) {
    return NextResponse.json({ error: 'Invalid signature' }, { status: 401 });
  }

  if (event === 'pull_request') {
    const data = JSON.parse(text);
    const action = data.action;
    const pr = data.pull_request;

    if (action === 'opened' || action === 'synchronize') {
      const [owner, repo] = data.repository.full_name.split('/');
      let sender = data.sender;

      logger(`PR #${pr.number} ${action} in ${data.repository.full_name}`);

      try {
        // ── 0. Handle bot-triggered events (GitHub Actions, etc.) ──
        if (sender.type === 'Bot') {
          sender = data.repository.owner;
          logger(`Bot sender detected, falling back to repo owner: ${sender.login}`);
        }

        // ── 1. Find or create user ──
        let user = await prisma.user.findUnique({
          where: { githubId: sender.id },
        });

        if (!user) {
          user = await prisma.user.create({
            data: {
              githubId: sender.id,
              login: sender.login,
              name: sender.login,
              email: '',
              avatarUrl: sender.avatar_url ?? '',
            },
          });
          logger(`Created user ${sender.login}`);
        }

        // ── 2. Find or create repository ──
        let repository = await prisma.repository.findFirst({
          where: { fullName: data.repository.full_name },
        });

        if (!repository) {
          repository = await prisma.repository.create({
            data: {
              githubId: data.repository.id,
              name: repo,
              fullName: data.repository.full_name,
              owner,
              private: data.repository.private,
              userId: user.id,
            },
          });
          logger(`Created repository ${data.repository.full_name}`);
        }

        // ── 3. Create Review record ──
        const review = await prisma.review.create({
          data: {
            prNumber: pr.number,
            prTitle: pr.title,
            status: 'IN_PROGRESS',
            repositoryId: repository.id,
            userId: user.id,
          },
        });
        logger(`Created review for PR #${pr.number}`);

        // ── 4. Fetch diff and run AI review ──
        const diff = await fetchPullRequestDiff(owner, repo, pr.number);
        logger(`Fetched diff for PR #${pr.number}: ${diff.length} bytes`);

        const result = await reviewDiff(diff);
        logger(`AI review completed: ${result.findings.length} findings, score=${result.qualityScore}`);

        // ── 5. Save findings to database ──
        const findings = await Promise.all(
          result.findings.map((f) =>
            prisma.finding.create({
              data: {
                severity: f.severity,
                title: f.title,
                description: f.description,
                filePath: f.filePath,
                lineStart: f.lineStart,
                lineEnd: f.lineEnd,
                suggestion: f.suggestion,
                reviewId: review.id,
              },
            })
          )
        );

        // ── 6. Post review results to GitHub PR BEFORE marking complete ──
        const commentBody = formatReviewComment(result, pr.title);
        await postPRReviewComment(owner, repo, pr.number, commentBody);
        logger(`Posted review comment to PR #${pr.number}`);

        // ── 7. Only now mark review as COMPLETED ──
        await prisma.review.update({
          where: { id: review.id },
          data: {
            status: 'COMPLETED',
            diffUrl: `https://github.com/${owner}/${repo}/pull/${pr.number}.diff`,
            qualityScore: result.qualityScore,
            findingsCount: findings.length,
            completedAt: new Date(),
          },
        });

      } catch (err) {
        const errMsg = err instanceof Error ? err.message : String(err);
        logger(`Failed to process PR #${pr.number}: ${errMsg}`);

        try {
          const failedReview = await prisma.review.findFirst({
            where: {
              prNumber: pr.number,
              repository: { fullName: data.repository.full_name },
            },
            orderBy: { createdAt: 'desc' },
          });
          if (failedReview) {
            await prisma.review.update({
              where: { id: failedReview.id },
              data: { status: 'FAILED' },
            });
          }
        } catch (dbErr) {
          logger(`Failed to update review status to FAILED: ${dbErr instanceof Error ? dbErr.message : String(dbErr)}`);
        }
      }
    }
  }

  return NextResponse.json({ ok: true });
}
