import { NextResponse } from 'next/server';
import { createHmac, timingSafeEqual } from 'crypto';
import { prisma } from '@/lib/prisma';
import { fetchPullRequestDiff, postPRReviewComment } from '@/lib/github';
import { reviewDiff, ReviewResult } from '@/lib/ai';
import { persistLog } from '@/lib/log';

function verifySignature(payload: string, signature: string | null, secret: string): boolean {
  if (!signature) return false;
  const algo = signature.startsWith('sha256=') ? 'sha256' : 'sha1';
  const prefix = algo === 'sha256' ? 'sha256=' : 'sha1=';
  const hmac = createHmac(algo, secret).update(payload).digest('hex');
  const expected = prefix + hmac;
  if (signature.length !== expected.length) return false;
  return timingSafeEqual(Buffer.from(signature), Buffer.from(expected));
}

/**
 * Format AI review result into a GitHub-friendly Markdown comment.
 */
function formatReviewComment(result: ReviewResult, prTitle: string): string {
  const { qualityScore, summary, findings } = result;

  let body = `## 🤖 PRwise AI Review\n\n`;
  body += `**PR**: ${prTitle}\n\n`;
  body += `**Quality Score**: ${qualityScore}/100\n\n`;
  body += `> ${summary}\n\n`;

  if (findings.length > 0) {
    body += `### 📝 Findings (${findings.length})\n\n`;

    findings.forEach((f) => {
      const icon = f.severity === 'ERROR' ? '🔴' : f.severity === 'WARNING' ? '🟡' : '🔵';
      body += `${icon} **${f.title}**\n`;
      if (f.filePath) {
        body += `- 📁 File: \`${f.filePath}\``;
        if (f.lineStart) body += ` (line ${f.lineStart})`;
        body += '\n';
      }
      body += `- ${f.description}\n`;
      if (f.suggestion) {
        body += `- 💡 Suggestion: ${f.suggestion}\n`;
      }
      body += '\n';
    });
  } else {
    body += '✅ No issues found. Code looks great!\n';
  }

  body += '---\n*Generated by PRwise AI*';
  return body;
}

export async function POST(request: Request) {
  const text = await request.text();
  const signature = request.headers.get('x-hub-signature-256');
  const event = request.headers.get('x-github-event');
  const webhookSecret = process.env.GITHUB_WEBHOOK_SECRET;

  if (webhookSecret && !verifySignature(text, signature, webhookSecret)) {
    await persistLog({ level: 'ERROR', source: 'webhook', message: 'Invalid webhook signature' });
    return NextResponse.json({ error: 'Invalid signature' }, { status: 401 });
  }

  if (event !== 'pull_request') {
    return NextResponse.json({ ok: true });
  }

  let data: any;
  try {
    data = JSON.parse(text);
  } catch {
    await persistLog({ level: 'ERROR', source: 'webhook', message: 'Failed to parse webhook payload as JSON' });
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 });
  }

  const action = data.action as string | undefined;
  const pr = data.pull_request;

  if (!pr || !action) {
    await persistLog({ level: 'WARN', source: 'webhook', message: 'Missing pull_request or action' });
    return NextResponse.json({ error: 'Missing pull_request or action' }, { status: 400 });
  }

  if (action !== 'opened' && action !== 'synchronize') {
    return NextResponse.json({ ok: true });
  }

  const [owner, repo] = data.repository.full_name.split('/');
  let sender = data.sender;

  try {
    // ── 0. Handle bot-triggered events (GitHub Actions, etc.) ──
    if (sender.type === 'Bot') {
      sender = data.repository.owner;
      await persistLog({ level: 'WARN', source: 'webhook', message: `Bot sender, fell back to ${sender.login}`, metadata: { repo: data.repository.full_name } });
    }

    // ── 1. Find or create user (upsert handles race conditions) ──
    const user = await prisma.user.upsert({
      where: { githubId: sender.id },
      update: {
        login: sender.login,
        name: sender.login,
        avatarUrl: sender.avatar_url ?? '',
      },
      create: {
        githubId: sender.id,
        login: sender.login,
        name: sender.login,
        email: '',
        avatarUrl: sender.avatar_url ?? '',
      },
    });

    // ── 2. Find or create repository ──
    // Fast path: look up by fullName (same repo always has same fullName)
    let repository = await prisma.repository.findFirst({
      where: { fullName: data.repository.full_name },
    });

    if (!repository) {
      // Upsert by githubId to safely handle:
      // - Race condition (two concurrent webhooks for the same new repo)
      // - Re-creation after deletion (first user deleted, second user triggers)
      repository = await prisma.repository.upsert({
        where: { githubId: data.repository.id },
        update: { fullName: data.repository.full_name, userId: user.id },
        create: {
          githubId: data.repository.id,
          name: repo,
          fullName: data.repository.full_name,
          owner,
          private: data.repository.private,
          userId: user.id,
        },
      });
      await persistLog({ level: 'INFO', source: 'webhook', message: `Created/claimed repo ${data.repository.full_name}` });
    }

    // ── 3. Check for existing review (idempotency for webhook retries) ──
    const existingReview = await prisma.review.findFirst({
      where: { prNumber: pr.number, repositoryId: repository.id },
      orderBy: { createdAt: 'desc' },
    });

    if (existingReview && (existingReview.status === 'COMPLETED' || existingReview.status === 'IN_PROGRESS')) {
      return NextResponse.json({ ok: true, skipped: true });
    }

    // ── 4. Create or reuse Review record ──
    const review = existingReview && existingReview.status === 'FAILED'
      ? existingReview
      : await prisma.review.create({
          data: {
            prNumber: pr.number,
            prTitle: pr.title,
            status: 'IN_PROGRESS',
            repositoryId: repository.id,
            userId: user.id,
          },
        });

    // Reset if reusing a failed review
    if (review.status === 'FAILED') {
      await prisma.review.update({
        where: { id: review.id },
        data: { status: 'IN_PROGRESS', findingsCount: 0, qualityScore: null, completedAt: null },
      });
    }

    // ── 5. Fetch diff and run AI review ──
    const diff = await fetchPullRequestDiff(owner, repo, pr.number);

    const result = await reviewDiff(diff);

    // ── 6. Save findings (delete old ones first if retry) ──
    await prisma.finding.deleteMany({ where: { reviewId: review.id } });
    const findings = await Promise.all(
      result.findings.map((f) =>
        prisma.finding.create({
          data: {
            severity: f.severity,
            title: f.title,
            description: f.description,
            filePath: f.filePath,
            lineStart: f.lineStart,
            lineEnd: f.lineEnd,
            suggestion: f.suggestion,
            reviewId: review.id,
          },
        })
      )
    );

    // ── 7. Update DB to COMPLETED before posting comment ──
    // This ensures DB state is consistent even if the comment post fails.
    // If the comment post fails, the catch block will mark it as FAILED.
    await prisma.review.update({
      where: { id: review.id },
      data: {
        status: 'COMPLETED',
        diffUrl: `https://github.com/${owner}/${repo}/pull/${pr.number}.diff`,
        qualityScore: result.qualityScore,
        findingsCount: findings.length,
        completedAt: new Date(),
      },
    });

    // ── 8. Post review results to GitHub PR ──
    const commentBody = formatReviewComment(result, pr.title);
    await postPRReviewComment(owner, repo, pr.number, commentBody);

  } catch (err) {
    const errMsg = err instanceof Error ? err.message : String(err);
    await persistLog({
      level: 'ERROR', source: 'webhook',
      message: `Failed to process PR #${pr.number}: ${errMsg}`,
      metadata: { repo: `${owner}/${repo}`, prNumber: pr.number, action },
    });

    try {
      const failedReview = await prisma.review.findFirst({
        where: {
          prNumber: pr.number,
          repository: { fullName: data.repository.full_name },
        },
        orderBy: { createdAt: 'desc' },
      });
      if (failedReview) {
        await prisma.review.update({
          where: { id: failedReview.id },
          data: { status: 'FAILED' },
        });
      }
    } catch (dbErr) {
      await persistLog({
        level: 'ERROR', source: 'webhook',
        message: `Failed to mark review FAILED: ${dbErr instanceof Error ? dbErr.message : String(dbErr)}`,
      });
    }
  }

  return NextResponse.json({ ok: true });
}
